services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    networks:
      - fintech
    # restart: unless-stopped

  frontend:
    build: ./Frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
    - BACKEND_URL=http://backend:8000/calculate_advance
    networks:
      - fintech

networks:
  fintech:
    driver: bridge