services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: BACKEND_URL
        value: http://backend:$PORT
    plan: free

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./Frontend/Dockerfile
    envVars:
      - key: BACKEND_URL
        value: http://backend:$PORT
    plan: free