# render.yaml
services:
  - type: web
    name: backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: BACKEND_URL
        value: http://backend:8000
    plan: free
    dockerfilePath: ./backend/Dockerfile
    ports:
      - port: 8000
        host: 8000

  - type: web
    name: frontend
    env: python
    buildCommand: "cd frontend && pip install -r requirements.txt"
    startCommand: "streamlit run frontend.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: BACKEND_URL
        value: http://backend:8000
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    ports:
      - port: 8501
        host: 8501
    dependsOn:
      - backend